### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by umatbro** [MIachaI/MPK_Crawler#6]
# Do zrobienia
## ListHandler
- [x] ~~odrzucanie niepotrzebnych przystanków~~ wybieranie pesymistycznych wariantów z listy
- [x] funkcja ~~*exportExcel()*~~  **excelFormattedText()**, która wyrzucałaby tekst nadający się do wklejenia do excela
- [ ] dostęp do pojedynczych przystanków z listy (ListHandler, ew. MPKList) 
- [x] oddzielenie busów od tramwajów w *excelFormattedText()* 75af29c875b04874b17e96f7df5329f0ff979f17

## BusInfo
- [x] zebranie informacji o typie pojazdu (bus/tramwaj)  :exclamation:
- [x] sprawdzenie nazw kolumn w MPK
- [x] pole z ostrzeżeniem o niestandardowych nazwach kolumn
- [x] metoda *getRawHtml()* - zdecydowac czy ma byc abstract czy jakies inne rozwiązanie
## WindowInterface
- [x] zmiana Swinga na JavaFX
- [x] zmiana nazwy pliku wyjściowego
- [x] pobieranie większej ilości linkow (np. większe pole tekstowe, kazda linia = nowy link), check [TextArea](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/TextArea.html) 73a609bfd86badca36ca709be32a9f12654053bf
- [x] wyszukiwarka
- [x] okna zamiast alertów
- [x] wstążka
- [x] ścieżka zapisu (bądź okno)
## WWa
- [x]  wyświetlenie wyników dla jednego przystanku (nowa klasa ZTMinfo) 2d4b077aba2f1f526aef1a43f510f02b5106ace3
- [x] zebranie listy wszystkich przystanków (nowa klasa ZTMList)

## ListContainer
- [x] możliwość dodawania kolejnych list kursów (ListHandlerów) dla różnych przystanków  f13356afa6240829ef2b4225c9983b1263e0336a
- [ ] przeniesienie *excelFormattedText()* do tej klasy i odpowiednie dostosowanie do wyświetlania list z kilku przystanków
- [ ] możliwość wybrania zakresu godzin rozpatrywanych przy analizie przejazdów

## PictureHandler
- [x] renderowanie obrazka z danego htmla [stackowerfloł](http://stackoverflow.com/questions/26465519/html-file-convert-it-to-image-file-locally) [gugel](https://code.google.com/archive/p/java-html2image/)

## Dokumentacja
- [ ] W chwili wolnej można posiedzieć mocnej nad dokumentacją (javadoki do wszystkich metod)

## GUI
- [ ] Dodanie w GUI jakiegoś `TextArea` na logi

# Możliwe ulepszenia
- [x] Zapisanie listy przystanków lokalnie (z możliwością odświeżenia)
    - przykładowy [plik json](https://gist.github.com/umatbro/d8573fee2a07717300da1c728897c2ba) 
- [ ] Plik json odświeżany automatycznie, gdy wykryje, że jego wersja jest nieaktualna (porównanie z informacją na stronie)
- [ ] odnośniki do google maps przy przystankach
## Zapis do arkusza excela
Linki:
* [Stack](http://stackoverflow.com/questions/1176080/create-excel-file-in-java)
* [Apache](http://poi.apache.org/spreadsheet/quick-guide.html)  HSSF+XSSF 
* [Poznan API] (http://egov.psnc.pl/node/29#linie_mpk)
* [Link do JSONa Poznan] (http://www.poznan.pl/mim/plan/map_service.html?mtype=pub_transport&co=cluster)
## JavaFX zamiast swing
* [Tut yt](https://www.youtube.com/watch?v=FLkOX4Eez6o)
